### ISSUE TITLE
please remove hardcoded default aws profile usage 

### ISSUE THREAD

**Issue by foood** [vladyslav-tripatkhi/terraform-iam-modules#5]
https://github.com/vladyslav-tripatkhi/terraform-iam-modules/blob/1ef29614fa0c4f7d3f05a1fdb7ceaf7b81d7be48/import_scripts/iam_roles/import_roles.py#L135

**Comment by foood** [comment]
also here:
import_groups.py
import_policies.py
import_users.py

**Comment by vladyslav-tripatkhi** [comment]
@foood, fixed it in the latest commit.
